### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by granny** [Scarsz/JDAAppender#9]
https://github.com/Scarsz/JDAAppender/blob/794d25d5179e0092927fdf22fd7c194da8966a77/src/main/java/me/scarsz/jdaappender/ChannelLoggingHandler.java#L148-L155

Relevant line in DSRV: https://github.com/DiscordSRV/DiscordSRV/blob/b09d2f6300317b516e3f19612435f802cb7897c4/src/main/java/github/scarsz/discordsrv/listeners/DiscordConsoleListener.java#L110

<details open>
<summary>Log</summary>

```
[04:36:28] [JDA MainWS-ReadThread/ERROR]: [DiscordSRV] [JDA] One of the EventListeners had an uncaught exception
java.util.ConcurrentModificationException
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:756)
	at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:778)
	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.updateMessage(ChannelLoggingHandler.java:194)
	at DiscordSRV.jar//me.scarsz.jdaappender.ChannelLoggingHandler.dumpStack(ChannelLoggingHandler.java:152)
	at DiscordSRV.jar//github.scarsz.discordsrv.listeners.DiscordConsoleListener.onGuildMessageReceived(DiscordConsoleListener.java:110)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:483)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:88)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:70)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.JDAImpl.handleEvent(JDAImpl.java:160)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:97)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:952)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:839)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:817)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:991)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.handleFrame(ReadingThread.java:755)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.main(ReadingThread.java:108)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.ReadingThread.runMain(ReadingThread.java:64)
	at DiscordSRV.jar//github.scarsz.discordsrv.dependencies.ws.client.WebSocketThread.run(WebSocketThread.java:45)
```

</details>

**Comment by Scarsz** [comment]
should be good
